### ISSUE TITLE
Clean up presidential candidate names in 2016 general precinct file

### ISSUE THREAD

**Issue by warwickmm** [openelections/openelections-data-vt#2]
The `President` entries in [2016/20161108__vt__general__precinct.csv](https://raw.githubusercontent.com/warwickmm/openelections-data-vt/a59c0510672ee57eb50dcf234e46d1152aacb3ed/2016/20161108__vt__general__precinct.csv) need to be cleaned up.

Currently, the candidates for president and vice-president are separated by a period, which is not a common format across the data files:
```
Washington,President,,Woodbury,,Hillary Clinton. Tim Kaine,Democratic,271,82048
```
Furthermore, the entries for the Republican ticket are missing  "Pence" from the vice-president candidate's name:
```
Addison,President,,Addison,,Donald Trump. Michael R ,Republican,337,82048
```
We should either omit the vice-president candidate names (which appears to be more common across the files), or come up with a standard schema for this if there isn't one already.

**Comment by dwillis** [comment]
@warwickmm yeah, this is a pretty common thing and something that the tickets work might be able to address. My preference is to omit VP names.

**Comment by warwickmm** [comment]
OK, I'll remove them.
